#Exclude these files from analysis
project_includes = [
  "pandas/**/*.py",
  "pandas/**/*.pyi",
  "typings/**/*.pyi",
]
#Exclude these files from analysis
project_excludes = [
  "pandas/tests/**/*.py",
  "pandas/io/clipboard/**/*.py",
]

# Search path
search_path = ["typings"]
# Site package path
#site_package_path = [
#	".venv/lib/python3.11/site-packages"
#]
# Python platform and version
python_version = "3.11"
# Errors configuration

replace_imports_with_any = [
	"pandas._config.config", # TODO
	"pandas._libs.*",
	"pandas._testing.*", # TODO
	"pandas.compat.numpy.function", # TODO
	"pandas.core._numba.executor", # TODO
	"pandas.core.array_algos.masked_reductions", # TODO
	"pandas.core.array_algos.putmask", # TODO
	"pandas.core.array_algos.quantile", # TODO
	"pandas.core.array_algos.replace", # TODO
	"pandas.core.array_algos.take", # TODO
	"pandas.core.arrays.*", # TODO
	"pandas.core.computation.*", # TODO
	"pandas.core.dtypes.astype", # TODO
	"pandas.core.dtypes.cast", # TODO
	"pandas.core.dtypes.common", # TODO
	"pandas.core.dtypes.concat", # TODO
	"pandas.core.dtypes.dtypes", # TODO
	"pandas.core.dtypes.generic", # TODO
	"pandas.core.dtypes.missing", # TODO
	"pandas.core.groupby.generic", # TODO
	"pandas.core.groupby.grouper", # TODO
	"pandas.core.groupby.groupby", # TODO
	"pandas.core.groupby.ops", # TODO
	"pandas.core.indexers.*", # TODO
	"pandas.core.indexes.*", # TODO
	"pandas.core.interchange.column", # TODO
	"pandas.core.interchange.dataframe_protocol", # TODO
	"pandas.core.interchange.from_dataframe", # TODO
	"pandas.core.internals.*", # TODO
	"pandas.core.ops.array_ops", # TODO
	"pandas.core.ops.common", # TODO
	"pandas.core.ops.missing", # TODO
	"pandas.core.reshape.*", # TODO
	"pandas.core.strings.*", # TODO
	"pandas.core.tools.*", # TODO
	"pandas.core.window.common", # TODO
	"pandas.core.window.ewm", # TODO
	"pandas.core.window.expanding", # TODO
	"pandas.core.window.numba_", # TODO
	"pandas.core.window.online", # TODO
	"pandas.core.window.rolling", # TODO
	"pandas.core.accessor", # TODO
	"pandas.core.algorithms", # TODO
	"pandas.core.apply", # TODO
	"pandas.core.arraylike", # TODO
	"pandas.core.base", # TODO
	"pandas.core.common", # TODO
	"pandas.core.construction", # TODO
	"pandas.core.flags", # TODO
	"pandas.core.frame", # TODO
	"pandas.core.generic", # TODO
	"pandas.core.indexing", # TODO
	"pandas.core.missing", # TODO
	"pandas.core.nanops", # TODO
	"pandas.core.resample", # TODO
	"pandas.core.roperator", # TODO
	"pandas.core.sample", # TODO
	"pandas.core.series", # TODO
	"pandas.core.sorting", # TODO
	"pandas.errors", # TODO
	"pandas.io.clipboard", # TODO
	"pandas.io.excel._base", # TODO
	"pandas.io.excel._odfreader", # TODO
	"pandas.io.excel._openpyxl", # TODO
	"pandas.io.excel._pyxlsb", # TODO
	"pandas.io.excel._xlrd", # TODO
	"pandas.io.excel._xlsxwriter", # TODO
	"pandas.io.formats.excel", # TODO
	"pandas.io.formats.format", # TODO
	"pandas.io.formats.style", # TODO
	"pandas.io.formats.style_render", # TODO
	"pandas.io.formats.xml", # TODO
	"pandas.io.json.*", # TODO
	"pandas.io.parsers.*", # TODO
	"pandas.io.sas.sas_xport", # TODO
	"pandas.io.sas.sas7bdat", # TODO
	"pandas.io.clipboards", # TODO
	"pandas.io.html", # TODO
	"pandas.io.parquet", # TODO
	"pandas.io.pytables", # TODO
	"pandas.io.sql", # TODO
	"pandas.io.xml", # TODO
	"pandas.plotting.*", # TODO
	"pandas.tests.*",
	"pandas.tseries.frequencies", # TODO
	"pandas.tseries.holiday", # TODO
	"pandas.util._decorators", # TODO
	"pandas.util._doctools", # TODO
	"pandas.util._test_decorators", # TODO
	"pandas.util._validators", # TODO
	"pandas.util", # TODO
	"pandas._version",
	"pandas.conftest",
	"pandas"
]

[errors]
# Ignore missing imports
missing-module-attribute = false